### ISSUE TITLE
Polish repository of old scripts now redundant with PyPi and RtD

### ISSUE THREAD

**Issue by gregorgorjanc** [AlphaGenes/AlphaPeel#29]
We have some scripts that we don't need anymore now that we have PyPi and Read the Docs.

Some candidates:

* https://github.com/AlphaGenes/AlphaPeel/blob/main/build_pipeline.sh REMOVE?

* https://github.com/AlphaGenes/AlphaPeel/tree/main#readme POLISH (remove the build stuff and point to documentation? Should we also port the environments stuff/mamba into the installation and development/contribution?)

* https://github.com/AlphaGenes/AlphaPeel/blob/main/docs/Makefile

* https://github.com/AlphaGenes/AlphaPeel/blob/main/docs/make.bat

Anything else?

**Comment by XingerTang** [comment]
@gregorgorjanc According to the ``Sphinx`` documentation, ``Makefile`` and ``make.bat`` are
> Convenience scripts to simplify some common Sphinx operations, such as rendering the content.

Even though we are applying Read the Docs right now, it is building documentation by using ``Sphinx``, so these two files should be kept.

Also, as we have ``pyproject.toml`` now, we don't need ``setup.py`` anymore.

**Comment by gregorgorjanc** [comment]
@XingerTang OK, Sphinx scripts stay for now.

I have done some polishing in the README, but more should be done re build system. Can you see what is the best way forward and clean the other files?

**Comment by XingerTang** [comment]
@gregorgorjanc 
I think we don't need the build instructions as these are written for building the ``zip`` file. 
Even though it can also build the user guide and distributions,
* For building the user guide, as we implemented Read the Docs now, we can just put some links to the documentation there.
* For building the distributions, both the source distribution and the wheel distribution of the package are now available on the [PyPI](https://pypi.org/project/AlphaPeel/#files). If the users want to build the wheels by themselves, the instructions can still be simplified a lot so that the building can be done without any reference to ``build_pipeline.sh``.

**Comment by gregorgorjanc** [comment]
I agree @XingerTang! Can you work on polishing this?

Thanks! We have done a great job here and have a very nice clean slate to move to more substantive stuff;)
