### ISSUE TITLE
rename -call_phase option to -hap

### ISSUE THREAD

**Issue by AprilYUZhang** [AlphaGenes/AlphaPeel#89]

**Comment by AprilYUZhang** [comment]
related to #73

**Comment by AprilYUZhang** [comment]
![image](https://github.com/AlphaGenes/AlphaPeel/assets/138952740/4ca20579-1abd-480c-a85a-0b19df198f11)
I find this option, But I don't know whether I should change the help, maybe "Flag to call the phase as well as the genotypes to get haplotypes" is more exactly? or others

**Comment by gregorgorjanc** [comment]
@AprilYUZhang yes, we should also change the help string. I propose this. 

`"Flag to call the haplotypes"` since this is what we are moving towards to once we implement https://github.com/AlphaGenes/AlphaPeel/issues/82#issuecomment-1752589131

Also, please look across all the codebase where the string `-call_pahse` appears: see https://github.com/search?q=repo%3AAlphaGenes%2FAlphaPeel%20call_phase&type=code

Finally, add this new option `-hap` to the documentation under inputs and outputs

**Comment by gregorgorjanc** [comment]
We think this one is now sorted so closing this issue.
